In [8]:
import numpy as np
import matplotlib.pyplot as plt
import opmap
from opmap.opmap import RawCam

In [129]:
df_path = "/Users/tomii/tmp/AnalysisResult/pv_stim_pandas.csv"
index_start = 0
index_end = 45

In [130]:
df = pd.read_csv(df_path)
df.loc[index_start:index_end, ["sample", "session", "fb_angle", "frame_start"]]

        sample  session  fb_angle  frame_start
0   20140911-2        8  1.049658          322
1   20140911-2       14  1.049658          306
2   20140911-2       15  1.049658          282
3   20140911-2       17  1.049658          282
4   20140911-2       34  1.049658          302
5   20140911-2       35  1.049658          302
6   20140911-2       36  1.049658          282
7   20140911-2       38  1.049658          302
8   20160907-3        6  1.555173          300
9   20160907-3       10  1.555173          360
10  20160907-3       11  1.555173          400
11  20160907-3       17  1.555173          360
12  20160907-3       22  1.555173          329
13  20161019-1       18  0.960070          370
14  20161019-1       19  0.960070          370
15  20161019-2        6  1.570796          170
16  20161019-2        7  1.570796          160
17  20161019-2        8  1.570796          140
18  20161019-2        9  1.570796          190
19  20161019-2       10  1.570796          150
20  20161019-2       11  1.570796          250
21  20161019-2       12  1.570796          130
22  20161019-2       13  1.570796          140
23  20161019-2       14  1.570796          150
24  20161019-2       15  1.570796          160
25  20161019-2       16  1.570796          170
26  20161019-2       17  1.570796          180
27  20161019-2       18  1.570796          190
28  20161019-2       19  1.570796          200
29  20161019-2       20  1.570796          210
30  20161019-2       21  1.570796          230
31  20161019-2       22  1.570796          250
32  20161019-2       23  1.570796          270
33  20161019-2       24  1.570796          290
34  20161019-3       24  1.015041          260
35  20161019-3       25  1.015041          255
36  20161021-1        9  1.237212          175
37  20161021-1       10  1.237212          175
38  20161021-1       11  1.237212          175
39  20161021-1       12  1.237212          185
40  20161021-1       13  1.237212          172
41  20161021-1       14  1.237212          185
42  20161021-1       16  1.237212          195
43  20161021-2       10  1.341269          190
44  20161021-2       11  1.341269          200
45  20161021-2       12  1.341269          210

In [126]:
cam = RawCam(
    path ="/Volumes/HD-PLFU3/ExperimentData/20161021-2/C001H001S0010/",
    cam_type = 'sa4',
    image_width = 512, 
    image_height = 512, 
    frame_start = 0,
    frame_end = 10    
)
points = cam.selectPoints()
fb_angle = np.angle( ( points[1][0] - points[0][0] )+1j*( points[1][1] - points[0][1] ) )
fb_angle

1.3412689725516063

In [127]:
df.loc[index_start:index_end, "fb_angle"] = fb_angle
df.loc[index_start:index_end, ["sample", "fb_angle"]]
df.to_csv(df_path, index=False)